name: al_things
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  get: ^4.6.6
  dartz: ^0.10.1
  http: ^1.2.2
  network_info_plus: ^4.0.0
  permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/logo/logo.png
  - assets/images/
